### ISSUE TITLE
Updates

### ISSUE THREAD

**Issue by GTez** [agentgonzo/steam-squid#1]
Hey there!

I see that you updated to add .steampipe.steamcontent.com - How did you know to do that?  I had a steam pipe issue at my local place of business and found your depot as a fix. 

Thanks in advance!
-GTez

**Comment by agentgonzo** [comment]
I noticed that the proxy wasn't working properly for proxying steam traffic
so looked at the logs (/var/log/squid/access.log). It full of requests to
the new domain name.

**Comment by lynx29** [comment]
Good day! 
Could you help me. why im not getting mem hit when running steam-squid this is my access.log 

21/Jun/2016:14:24:34 +0000  26134 192.168.1.20 TCP_MISS/200 9030673 GET http://media2.steampowered.com/client/bins_pub_ubuntu12.zip.vz.9e1268b3a8e3895e54e2828dbe6030a79c3552bf_9030238 - ORIGINAL_DST/205.185.216.42 application/octet-stream 

downloading on first machine then i try to download to a second machine  still tcp miss but i think they are just the same file this is the access.log on second machine.

21/Jun/2016:14:31:16 +0000  57929 192.168.1.14 TCP_MISS/200 9030768 GET http://media3.steampowered.com/client/bins_pub_ubuntu12.zip.vz.9e1268b3a8e3895e54e2828dbe6030a79c3552bf_9030238 - ORIGINAL_DST/185.13.160.253 application/octet-stream

Thnx!

**Comment by agentgonzo** [comment]
It is set up to only cache the game downloads (steampipe), so anything from
domains of the following type:
.cs.steampowered.com
.steampipe.steamcontent.com

The content that you're fetching there is from media3.steampowered.com, so
won't get cached.

You can probably add these domains to the steam.conf and steam_store_id
files in the docker image if you want to cache the media as well.

**Comment by lynx29** [comment]
thnx! for a quick reply im just a newbie testing this squid caching. I try it again tom. maybe i need more research on how to edit those 2 files.
